version: 2
builds:
  - main: ./cmd/eavesdrop
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X "main.VERSION={{.Version}}"
    env:
      - CGO_ENABLED=0
archives:
  - id: tar.gz
    formats: ["tar.gz"]
  - id: binary
    formats: ["binary"]
